language: c
dist: focal 
addons:
  apt:
    packages:
    - mingw-w64
    - wine64
install:
  - mkdir build && cd $_
  - cmake .. -DCMAKE_TOOLCHAIN_FILE="../mingw-w64-x86_64-toolchain.cmake" -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
script: cmake --build .
